# Generated by Django 6.0 on 2026-01-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Domain Controller Admin', max_length=100)),
                ('hostname', models.CharField(blank=True, help_text='IP or Website URL', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('encrypted_password', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
