# Generated by Django 6.0 on 2026-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='warranty_expiry',
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_name',
            field=models.CharField(default='Unknown Device', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_monitored',
            field=models.BooleanField(default=False, help_text='Check to add this device to the Network Monitor automatically.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='AssetHistory',
        ),
    ]
