# Generated by Django 6.0 on 2026-01-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_assigned_to_remove_asset_device_type_and_more'),
        ('monitoring', '0002_monitorcategory_remove_networktarget_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='monitor_category',
            field=models.ForeignKey(blank=True, help_text='Select which group this device belongs to in the Network Monitor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.monitorcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
    ]
