# Generated by Django 6.0 on 2026-01-07 12:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fas fa-desktop', help_text='FontAwesome class (e.g. fas fa-server)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Device Categories',
            },
        ),
        migrations.RemoveField(
            model_name='networktarget',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='networktarget',
            name='latency_ms',
        ),
        migrations.AddField(
            model_name='networktarget',
            name='host',
            field=models.CharField(default='127.0.0.1', help_text='IP Address (192.168.1.1) or Hostname (server.local)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networktarget',
            name='last_latency',
            field=models.FloatField(blank=True, help_text='Response time in ms', null=True),
        ),
        migrations.AlterField(
            model_name='networktarget',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 1, 7, 12, 51, 43, 783570, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networktarget',
            name='name',
            field=models.CharField(help_text='Friendly Name (e.g. Main Server)', max_length=100),
        ),
        migrations.AddField(
            model_name='networktarget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.monitorcategory'),
        ),
        migrations.DeleteModel(
            name='DownLog',
        ),
    ]
