# Generated by Django 6.0 on 2026-01-06 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Dell Latitude 5420 - IT-001', max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('PRINTER', 'Printer'), ('SERVER', 'Server'), ('SWITCH', 'Network Switch'), ('MOBILE', 'Mobile Phone'), ('PERIPHERAL', 'Peripheral (Monitor, Dock, etc)')], max_length=20)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ISSUED', 'Issued to Staff'), ('REPAIR', 'Out for Repair'), ('BROKEN', 'Broken / Decommissioned'), ('LOST', 'Lost / Stolen')], default='IN_STOCK', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_change', models.CharField(max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_new', to=settings.AUTH_USER_MODEL)),
                ('previous_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_prev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
