# Generated by Django 6.0 on 2026-01-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Office 365 Admin', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('encrypted_password', models.CharField(max_length=500)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
