# Generated by Django 6.0 on 2026-01-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Domain Controller', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='e.g. 192.168.0.1')),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, help_text='Ping speed in milliseconds', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop monitoring this device')),
            ],
        ),
        migrations.CreateModel(
            name='DownLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.networktarget')),
            ],
        ),
    ]
