# Generated by Django 6.0 on 2026-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitorcategory_remove_networktarget_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Task name, e.g. 'Check Backups'", max_length=200)),
                ('is_checked', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_email', models.EmailField(default='admin@example.com', help_text='Email address to receive daily reports', max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='monitorcategory',
            options={'verbose_name_plural': 'Monitor Categories'},
        ),
        migrations.RemoveField(
            model_name='networktarget',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='networktarget',
            name='last_latency',
        ),
        migrations.AddField(
            model_name='networktarget',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networktarget',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitorcategory',
            name='icon',
            field=models.CharField(default='fas fa-server', help_text='FontAwesome class (e.g. fas fa-server)', max_length=50),
        ),
        migrations.AlterField(
            model_name='networktarget',
            name='host',
            field=models.CharField(help_text='IP Address or Hostname', max_length=100),
        ),
        migrations.AlterField(
            model_name='networktarget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networktarget',
            name='name',
            field=models.CharField(help_text='Device Name (e.g. Primary Server)', max_length=100),
        ),
    ]
