# Generated by Django 6.0 on 2026-01-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_dailychecklist_systemsetting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networktarget',
            old_name='last_check',
            new_name='last_checked',
        ),
    ]
